import {
  PermissionMetadata, ResourceMetadata, Role, RoleMetadata,
} from '@src/types';
import {
  LibraryBooks, Article, Group, LocalOffer,
  BookOpen,
  Sync,
  Folder,
  Calendar,
  Download,
  DrawShapes,
  CheckCircle,
  RemoveRedEye,
  Plus,
  EditOutline,
  DownloadDone,
  Settings,
  Checklist,
  Delete,
  Upload,
  Award,
} from '@openedx/paragon/icons';

export const CONTENT_COURSE_PERMISSIONS = {
  VIEW_COURSE: 'courses.view_course',
  CREATE_COURSE: 'courses.create_course',
  EDIT_COURSE_CONTENT: 'courses.edit_course_content',
  PUBLISH_COURSE_CONTENT: 'courses.publish_course_content',

  MANAGE_COURSE_LIBRARY_UPDATES: 'courses.manage_library_updates',

  VIEW_COURSE_UPDATES: 'courses.view_course_updates',
  MANAGE_COURSE_UPDATES: 'courses.manage_course_updates',

  VIEW_COURSE_PAGES_RESOURCES: 'courses.view_pages_and_resources',
  MANAGE_COURSE_PAGES_RESOURCES: 'courses.manage_pages_and_resources',

  VIEW_COURSE_FILES: 'courses.view_files',
  CREATE_COURSE_FILES: 'courses.create_files',
  EDIT_COURSE_FILES: 'courses.edit_files',
  DELETE_COURSE_FILES: 'courses.delete_files',

  VIEW_COURSE_SCHEDULE_AND_DETAILS: 'courses.view_schedule_and_details',
  EDIT_COURSE_SCHEDULE: 'courses.edit_schedule',
  EDIT_COURSE_DETAILS: 'courses.edit_details',

  VIEW_COURSE_GRADING_SETTINGS: 'courses.view_grading_settings',
  EDIT_COURSE_GRADING_SETTINGS: 'courses.edit_grading_settings',

  VIEW_COURSE_TEAM: 'courses.view_course_team',
  MANAGE_COURSE_TEAM: 'courses.manage_course_team',
  MANAGE_COURSE_GROUP_CONFIGURATION: 'courses.manage_group_configurations',

  MANAGE_COURSE_TAGS: 'courses.manage_tags',

  MANAGE_COURSE_ADVANCED_SETTINGS: 'courses.manage_advanced_settings',
  MANAGE_COURSE_CERTIFICATES: 'courses.manage_certificates',

  IMPORT_COURSE: 'courses.import_course',
  EXPORT_COURSE: 'courses.export_course',
  EXPORT_COURSE_TAGS: 'courses.export_tags',

  VIEW_COURSE_CHECKLISTS: 'courses.view_checklists',
};

export const courseResourceTypes: ResourceMetadata[] = [
  {
    key: 'course_access_content',
    label: 'Course Access & content',
    description: 'Permissions related to accessing the course and managing core course content, including creating, editing, and publishing materials.',
    icon: BookOpen,
  },
  {
    key: 'course_library_updates',
    label: 'Library updates',
    description: 'Permissions for reviewing and managing updates made to content libraries connected to the course.',
    icon: LibraryBooks,
  },
  {
    key: 'course_updates_handouts',
    label: 'Course updates & handouts',
    description: 'Permissions for viewing and managing course updates and handouts that are visible to learners.',
    icon: Sync,
  },
  {
    key: 'course_pages_resources',
    label: 'Pages & resources',
    description: 'Permissions for viewing and managing course pages and additional learning resources.',
    icon: Article,
  },
  {
    key: 'course_files',
    label: 'Files',
    description: 'Permissions for viewing and managing course pages and additional learning resources.',
    icon: Folder,
  },
  {
    key: 'course_schedule_details',
    label: 'Schedule & details',
    description: 'Permissions for viewing and editing the course schedule and course information.',
    icon: Calendar,
  },
  {
    key: 'course_grading',
    label: 'Grading',
    description: 'Permissions related to viewing and managing grading configuration and grading policies.',
    icon: Award,
  },
  {
    key: 'course_team_group',
    label: 'Course team & groups',
    description: 'Permissions for viewing and managing the course team, learner groups, and group configurations.',
    icon: Group,
  },
  {
    key: 'course_tags_taxonomies',
    label: 'Tags',
    description: 'Permissions for managing tags used to organize course content.',
    icon: LocalOffer,
  },
  {
    key: 'course_advanced_certificates',
    label: 'Advanced & certificates',
    description: 'Permissions for managing advanced course settings and course certificates.',
    icon: CheckCircle,
  },
  {
    key: 'course_import_export',
    label: 'Import / export',
    description: 'Permissions for importing and exporting course content and related data.',
    icon: Download,
  },
  {
    key: 'course_other',
    label: 'Other',
    description: 'Additional permissions not included in other categories, such as viewing checklists.',
    icon: DrawShapes,
  },
];

export const coursePermissions: PermissionMetadata[] = [
  {
    key: CONTENT_COURSE_PERMISSIONS.VIEW_COURSE,
    resource: 'course_access_content',
    description: 'See the course in the Studio home and access the course outline in read-only mode. Includes the "View Live" option to preview the course as a learner in the LMS.',
    label: 'View course',
    icon: RemoveRedEye,
  },
  {
    key: CONTENT_COURSE_PERMISSIONS.CREATE_COURSE,
    resource: 'course_access_content',
    description: 'Create a new course in Studio.',
    label: 'Create course',
    icon: Plus,
  },
  {
    key: CONTENT_COURSE_PERMISSIONS.EDIT_COURSE_CONTENT,
    resource: 'course_access_content',
    description: 'Edit the course outline, units, and components.',
    label: 'Edit course content',
    icon: EditOutline,
  },
  {
    key: CONTENT_COURSE_PERMISSIONS.PUBLISH_COURSE_CONTENT,
    resource: 'course_access_content',
    description: 'Make course content visible to learners.',
    label: 'Publish course content',
    icon: DownloadDone,
  },

  {
    key: CONTENT_COURSE_PERMISSIONS.MANAGE_COURSE_LIBRARY_UPDATES,
    resource: 'course_library_updates',
    description: 'Accept or reject pending updates from content libraries linked to this course.',
    label: 'Manage library updates',
    icon: Checklist,
  },

  {
    key: CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_UPDATES,
    resource: 'course_updates_handouts',
    description: 'See course announcements and handouts visible to learners.',
    label: 'View course updates',
    icon: RemoveRedEye,
  },
  {
    key: CONTENT_COURSE_PERMISSIONS.MANAGE_COURSE_UPDATES,
    resource: 'course_updates_handouts',
    description: 'Create, edit, and delete course announcements and handouts.',
    label: 'Manage course updates',
    icon: Settings,
  },

  {
    key: CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_PAGES_RESOURCES,
    resource: 'course_pages_resources',
    description: 'See the Pages & Resources section in Studio.',
    label: 'View pages & resources',
    icon: RemoveRedEye,
  },
  {
    key: CONTENT_COURSE_PERMISSIONS.MANAGE_COURSE_PAGES_RESOURCES,
    resource: 'course_pages_resources',
    description: 'Enable or disable course features such as Discussions, the Wiki, Notes, Calculator, and Live. Create and edit Textbooks and Custom pages, and manage their configurations.',
    label: 'Manage pages & resources',
    icon: Settings,
  },

  {
    key: CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_FILES,
    resource: 'course_files',
    description: 'See the list of files and assets uploaded to the course.',
    label: 'View files',
    icon: RemoveRedEye,
  },
  {
    key: CONTENT_COURSE_PERMISSIONS.CREATE_COURSE_FILES,
    resource: 'course_files',
    description: 'Upload new files and assets to the course.',
    label: 'Create files',
    icon: Plus,
  },
  {
    key: CONTENT_COURSE_PERMISSIONS.EDIT_COURSE_FILES,
    resource: 'course_files',
    description: 'Perform non-destructive actions on files, such as locking or unlocking them.',
    label: 'Edit files',
    icon: EditOutline,
  },
  {
    key: CONTENT_COURSE_PERMISSIONS.DELETE_COURSE_FILES,
    resource: 'course_files',
    description: 'Permanently remove files and assets from the course.',
    label: 'Delete files',
    icon: Delete,
  },

  {
    key: CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_SCHEDULE_AND_DETAILS,
    resource: 'course_schedule_details',
    description: 'See the course schedule (start and end dates, enrollment dates, and pacing settings) and course details (summary, pacing, and prerequisites).',
    label: 'View schedule & details',
    icon: RemoveRedEye,
  },
  {
    key: CONTENT_COURSE_PERMISSIONS.EDIT_COURSE_SCHEDULE,
    resource: 'course_schedule_details',
    description: 'Update course start and end dates, enrollment dates, and pacing settings.',
    label: 'Edit schedule',
    icon: EditOutline,
  },
  {
    key: CONTENT_COURSE_PERMISSIONS.EDIT_COURSE_DETAILS,
    resource: 'course_schedule_details',
    description: 'Update course information including the course summary, pacing, and prerequisites.',
    label: 'Edit course details',
    icon: EditOutline,
  },

  {
    key: CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_GRADING_SETTINGS,
    resource: 'course_grading',
    description: 'See the grading configuration for the course, including assignment types and grading scale.',
    label: 'View grading settings',
    icon: RemoveRedEye,
  },
  {
    key: CONTENT_COURSE_PERMISSIONS.EDIT_COURSE_GRADING_SETTINGS,
    resource: 'course_grading',
    description: 'Update the grading configuration for the course, including assignment types and grading scale.',
    label: 'Edit grading settings',
    icon: EditOutline,
  },

  {
    key: CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_TEAM,
    resource: 'course_team_group',
    description: 'See the list of users with a role assigned to this course.',
    label: 'View course team',
    icon: RemoveRedEye,
  },
  {
    key: CONTENT_COURSE_PERMISSIONS.MANAGE_COURSE_TEAM,
    resource: 'course_team_group',
    description: 'Add, change, or remove role assignments for this course from the Roles and Permissions console.',
    label: 'Manage course team',
    icon: Settings,
  },
  {
    key: CONTENT_COURSE_PERMISSIONS.MANAGE_COURSE_GROUP_CONFIGURATION,
    resource: 'course_team_group',
    description: 'Create and manage content groups used to target course content to specific learners.',
    label: 'Manage group configuration',
    icon: Settings,
  },

  {
    key: CONTENT_COURSE_PERMISSIONS.MANAGE_COURSE_TAGS,
    resource: 'course_tags_taxonomies',
    description: 'Create, edit, and delete tags on this course.',
    label: 'Manage tags',
    icon: Settings,
  },

  {
    key: CONTENT_COURSE_PERMISSIONS.MANAGE_COURSE_ADVANCED_SETTINGS,
    resource: 'course_advanced_certificates',
    description: 'Access and edit the Advanced Settings page in Studio. This covers a wide range of technical course configurations, including proctoring, timed exams, LTI tools, enrollment limits, and custom display options.',
    label: 'Manage advanced settings',
    icon: Settings,
  },
  {
    key: CONTENT_COURSE_PERMISSIONS.MANAGE_COURSE_CERTIFICATES,
    resource: 'course_advanced_certificates',
    description: 'Create and edit course certificates, including certificate design and eligibility settings.',
    label: 'Manage certificates',
    icon: Settings,
  },

  {
    key: CONTENT_COURSE_PERMISSIONS.IMPORT_COURSE,
    resource: 'course_import_export',
    description: 'Import course content from a file. This is a high-privilege action that can overwrite most course content and settings.',
    label: 'Import course',
    icon: Download,
  },
  {
    key: CONTENT_COURSE_PERMISSIONS.EXPORT_COURSE,
    resource: 'course_import_export',
    description: 'Download the course content as a file for backup or reuse in another platform.',
    label: 'Export course',
    icon: Upload,
  },
  {
    key: CONTENT_COURSE_PERMISSIONS.EXPORT_COURSE_TAGS,
    resource: 'course_import_export',
    description: 'Download the tag data associated with this course.',
    label: 'Export tags',
    icon: Upload,
  },

  {
    key: CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_CHECKLISTS,
    resource: 'course_other',
    description: 'See the course launch checklist in Studio.',
    label: 'View checklists',
    icon: RemoveRedEye,
  },
];

export const courseRolesMetadata: RoleMetadata[] = [
  {
    role: 'course_admin',
    name: 'Course Admin',
    description: 'Can manage the course team and all course settings.',
    contextType: 'course',
  },
  {
    role: 'course_staff',
    name: 'Course Staff',
    description: 'Can publish content and manage the course lifecycle in Studio.',
    contextType: 'course',
  },
  {
    role: 'course_editor',
    name: 'Course Editor',
    description: 'Can create and edit course content, but cannot publish or change critical course settings.',
    contextType: 'course',
    disabled: true,
  },
  {
    role: 'course_auditor',
    name: 'Course Auditor',
    description: 'Can view course content and settings, but cannot make changes.',
    contextType: 'course',
    disabled: true,
  },
];

// Permission keys granted to each course role.
const COURSE_ROLE_PERMISSIONS: Record<string, string[]> = {
  course_admin: [
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE,
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_UPDATES,
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_PAGES_RESOURCES,
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_FILES,
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_GRADING_SETTINGS,
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_CHECKLISTS,
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_TEAM,
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_SCHEDULE_AND_DETAILS,
    CONTENT_COURSE_PERMISSIONS.EDIT_COURSE_CONTENT,
    CONTENT_COURSE_PERMISSIONS.MANAGE_COURSE_LIBRARY_UPDATES,
    CONTENT_COURSE_PERMISSIONS.MANAGE_COURSE_UPDATES,
    CONTENT_COURSE_PERMISSIONS.MANAGE_COURSE_PAGES_RESOURCES,
    CONTENT_COURSE_PERMISSIONS.CREATE_COURSE_FILES,
    CONTENT_COURSE_PERMISSIONS.EDIT_COURSE_FILES,
    CONTENT_COURSE_PERMISSIONS.EDIT_COURSE_GRADING_SETTINGS,
    CONTENT_COURSE_PERMISSIONS.MANAGE_COURSE_GROUP_CONFIGURATION,
    CONTENT_COURSE_PERMISSIONS.EDIT_COURSE_DETAILS,
    CONTENT_COURSE_PERMISSIONS.MANAGE_COURSE_TAGS,
    CONTENT_COURSE_PERMISSIONS.PUBLISH_COURSE_CONTENT,
    CONTENT_COURSE_PERMISSIONS.DELETE_COURSE_FILES,
    CONTENT_COURSE_PERMISSIONS.EDIT_COURSE_SCHEDULE,
    CONTENT_COURSE_PERMISSIONS.MANAGE_COURSE_ADVANCED_SETTINGS,
    CONTENT_COURSE_PERMISSIONS.MANAGE_COURSE_CERTIFICATES,
    CONTENT_COURSE_PERMISSIONS.IMPORT_COURSE,
    CONTENT_COURSE_PERMISSIONS.EXPORT_COURSE,
    CONTENT_COURSE_PERMISSIONS.EXPORT_COURSE_TAGS,
    CONTENT_COURSE_PERMISSIONS.MANAGE_COURSE_TEAM,
  ],
  course_staff: [
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE,
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_UPDATES,
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_PAGES_RESOURCES,
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_FILES,
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_GRADING_SETTINGS,
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_CHECKLISTS,
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_TEAM,
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_SCHEDULE_AND_DETAILS,
    CONTENT_COURSE_PERMISSIONS.EDIT_COURSE_CONTENT,
    CONTENT_COURSE_PERMISSIONS.MANAGE_COURSE_LIBRARY_UPDATES,
    CONTENT_COURSE_PERMISSIONS.MANAGE_COURSE_UPDATES,
    CONTENT_COURSE_PERMISSIONS.MANAGE_COURSE_PAGES_RESOURCES,
    CONTENT_COURSE_PERMISSIONS.CREATE_COURSE_FILES,
    CONTENT_COURSE_PERMISSIONS.EDIT_COURSE_FILES,
    CONTENT_COURSE_PERMISSIONS.EDIT_COURSE_GRADING_SETTINGS,
    CONTENT_COURSE_PERMISSIONS.MANAGE_COURSE_GROUP_CONFIGURATION,
    CONTENT_COURSE_PERMISSIONS.EDIT_COURSE_DETAILS,
    CONTENT_COURSE_PERMISSIONS.MANAGE_COURSE_TAGS,
    CONTENT_COURSE_PERMISSIONS.PUBLISH_COURSE_CONTENT,
    CONTENT_COURSE_PERMISSIONS.DELETE_COURSE_FILES,
    CONTENT_COURSE_PERMISSIONS.EDIT_COURSE_SCHEDULE,
    CONTENT_COURSE_PERMISSIONS.MANAGE_COURSE_ADVANCED_SETTINGS,
    CONTENT_COURSE_PERMISSIONS.MANAGE_COURSE_CERTIFICATES,
    CONTENT_COURSE_PERMISSIONS.IMPORT_COURSE,
    CONTENT_COURSE_PERMISSIONS.EXPORT_COURSE,
    CONTENT_COURSE_PERMISSIONS.EXPORT_COURSE_TAGS,
  ],
  course_editor: [
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE,
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_UPDATES,
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_PAGES_RESOURCES,
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_FILES,
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_GRADING_SETTINGS,
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_CHECKLISTS,
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_TEAM,
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_SCHEDULE_AND_DETAILS,
    CONTENT_COURSE_PERMISSIONS.EDIT_COURSE_CONTENT,
    CONTENT_COURSE_PERMISSIONS.MANAGE_COURSE_LIBRARY_UPDATES,
    CONTENT_COURSE_PERMISSIONS.MANAGE_COURSE_UPDATES,
    CONTENT_COURSE_PERMISSIONS.MANAGE_COURSE_PAGES_RESOURCES,
    CONTENT_COURSE_PERMISSIONS.CREATE_COURSE_FILES,
    CONTENT_COURSE_PERMISSIONS.EDIT_COURSE_FILES,
    CONTENT_COURSE_PERMISSIONS.EDIT_COURSE_GRADING_SETTINGS,
    CONTENT_COURSE_PERMISSIONS.MANAGE_COURSE_GROUP_CONFIGURATION,
    CONTENT_COURSE_PERMISSIONS.EDIT_COURSE_DETAILS,
    CONTENT_COURSE_PERMISSIONS.MANAGE_COURSE_TAGS,
  ],
  course_auditor: [
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE,
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_UPDATES,
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_PAGES_RESOURCES,
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_FILES,
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_GRADING_SETTINGS,
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_CHECKLISTS,
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_TEAM,
    CONTENT_COURSE_PERMISSIONS.VIEW_COURSE_SCHEDULE_AND_DETAILS,
  ],
};

export const courseRolesWithPermissions: Role[] = courseRolesMetadata.map((meta) => ({
  ...meta,
  scope: '',
  userCount: 1,
  permissions: COURSE_ROLE_PERMISSIONS[meta.role] ?? [],
}));
